# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: datum.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='datum.proto',
  package='',
  syntax='proto2',
  serialized_pb=_b('\n\x0b\x64\x61tum.proto\":\n\x0cNdarrayDatum\x12\x0c\n\x04\x64\x61ta\x18\x01 \x02(\x0c\x12\r\n\x05shape\x18\x02 \x02(\x0c\x12\r\n\x05\x64type\x18\x03 \x02(\x0c\"(\n\x08PdfDatum\x12\r\n\x05token\x18\x01 \x02(\x0c\x12\r\n\x05stamp\x18\x02 \x02(\x0c')
)




_NDARRAYDATUM = _descriptor.Descriptor(
  name='NdarrayDatum',
  full_name='NdarrayDatum',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='data', full_name='NdarrayDatum.data', index=0,
      number=1, type=12, cpp_type=9, label=2,
      has_default_value=False, default_value=_b(""),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='shape', full_name='NdarrayDatum.shape', index=1,
      number=2, type=12, cpp_type=9, label=2,
      has_default_value=False, default_value=_b(""),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='dtype', full_name='NdarrayDatum.dtype', index=2,
      number=3, type=12, cpp_type=9, label=2,
      has_default_value=False, default_value=_b(""),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=15,
  serialized_end=73,
)


_PDFDATUM = _descriptor.Descriptor(
  name='PdfDatum',
  full_name='PdfDatum',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='token', full_name='PdfDatum.token', index=0,
      number=1, type=12, cpp_type=9, label=2,
      has_default_value=False, default_value=_b(""),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='stamp', full_name='PdfDatum.stamp', index=1,
      number=2, type=12, cpp_type=9, label=2,
      has_default_value=False, default_value=_b(""),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=75,
  serialized_end=115,
)

DESCRIPTOR.message_types_by_name['NdarrayDatum'] = _NDARRAYDATUM
DESCRIPTOR.message_types_by_name['PdfDatum'] = _PDFDATUM
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

NdarrayDatum = _reflection.GeneratedProtocolMessageType('NdarrayDatum', (_message.Message,), dict(
  DESCRIPTOR = _NDARRAYDATUM,
  __module__ = 'datum_pb2'
  # @@protoc_insertion_point(class_scope:NdarrayDatum)
  ))
_sym_db.RegisterMessage(NdarrayDatum)

PdfDatum = _reflection.GeneratedProtocolMessageType('PdfDatum', (_message.Message,), dict(
  DESCRIPTOR = _PDFDATUM,
  __module__ = 'datum_pb2'
  # @@protoc_insertion_point(class_scope:PdfDatum)
  ))
_sym_db.RegisterMessage(PdfDatum)


# @@protoc_insertion_point(module_scope)
