# network architecture
#frontend related
videofront_conf: 
    random: True,
    channel_input: bgr
    size: [88,88] 
    downsampling: False
    hidden_channel_num: 64 
    res_block_type: basic2d
    res_layer_block_num: 2
    res_hidden_channels: [ 64, 128, 256, 512 ]
    res_stride: [ 1, 2, 2, 2 ]
    res_act_type: prelu
    res_downsample_type: avgpool
    use_upsampler: true

# encoder related
encoder: conformer
encoder_conf:
    output_size: &encoder_output_dim 512    # dimension of attention
    attention_heads: 8
    linear_units: 2048  # the number of units of position-wise feed forward
    num_blocks: 3      # the number of encoder blocks
    dropout_rate: 0.1
    positional_dropout_rate: 0.1
    attention_dropout_rate: 0.0
    input_layer:     # encoder architecture type
    normalize_before: true
    rel_pos_type: latest
    pos_enc_layer_type: rel_pos
    selfattention_layer_type: rel_selfattn
    activation_type: swish
    macaron_style: true
    use_cnn_module: true
    cnn_module_kernel: 3
    
  
# decoder related
decoder: contransformer
decoder_conf:
    conv_out_channels: [128,128,256,512]
    conv_kernel_sizes: [2,2,2,2]
    conv_layer_norm: true
    attention_heads: 8
    linear_units: 2048
    num_blocks: 6
    dropout_rate: 0.1
    self_attention_dropout_rate: 0.0
    src_attention_dropout_rate: 0.0
    self_att_RPE: true
    max_relative_position: 64

# hybrid CTC/attention
model_conf:
    only_pdfloss: true
    pdf_lsm_weigth: 0.1     # label smoothing option
    length_normalized_loss: false
    ctc_weight: 0.0

# minibatch related
batch_type: bucket
bucket_bsize_dynamic: True # 48:18000000 #  #24:10000000
max_batch_size: 24 #48:128
bucket_length_multiplier: 1.1
bucket_batch_size: 2  #48:8

# optimization related
accum_grad: 4
grad_clip: 5
max_epoch: 40
val_scheduler_criterion:
    - valid
    - acc_pdf
best_model_criterion:
-   - valid
    - acc_pdf
    - max
keep_nbest_models: 10

optim: adam
optim_conf:
   lr: 0.0006 
scheduler: warmuplr
scheduler_conf:
   warmup_steps: 6000

num_workers: 11