# network architecture
# encoder related
encoder: conformer
encoder_conf:
    hidden_size: &encoder_output_dim 512
    embed_conf:
        output_size: *encoder_output_dim 
        pos_enc_layer_type: &posembdtype rel_pos
        positional_dropout_rate: 0.1
    conformer_conf:
        hidden_size: *encoder_output_dim     # dimension of attention
        attention_heads: 8
        linear_units: 2048  # the number of units of position-wise feed forward
        dropout_rate: 0.1
        attention_dropout_rate: 0.0
        normalize_before: true
        rel_pos_type: latest
        pos_enc_layer_type: *posembdtype
        selfattention_layer_type: rel_selfattn
        activation_type: swish
        macaron_style: true
        use_cnn_module: true
        cnn_module_kernel: 3
    
    attentionfusion_conf:
        MHA_conf:
            n_head: 8
            dropout_rate: 0.0
        MHA_type: rel_selfattn
        positionwise_layer_args:
            positionwise_layer_type: linear
            linear_units: 2048
            dropout_rate: 0.1
        dropout_rate: 0.1
        normalize_before: True

avlayer_num_conf:
    alayer_num1: 3
    vlayer_num1: 3
    alayer_num2: 9

# decoder related
decoder: contransformer
decoder_conf:
    conv_out_channels: [128,128,256,512]
    conv_kernel_sizes: [2,2,2,2]
    conv_layer_norm: true
    attention_heads: 8
    linear_units: 2048
    num_blocks: 6
    dropout_rate: 0.1
    self_attention_dropout_rate: 0.0
    src_attention_dropout_rate: 0.0
    self_att_RPE: true
    max_relative_position: 64


#init model params
ignore_init_mismatch: True 
init_param: 
    - exp_vsr/tritritone3_lipfarmid_com00_100fps/valid.acc_pdf.best.pth
    - exp_far/a_com_sp_cat2/valid.acc.ave_5best.pth
   
name_map: 
    - {"video_frontend.resnet":"video_frontend.resnet",
        "video_frontend.video_frontend":"video_frontend.video_frontend"}
    - {"encoder.encoders.0":"encoder.alayerblock1.0",
        "encoder.encoders.1":"encoder.alayerblock1.1",
        "encoder.encoders.2":"encoder.alayerblock1.2",
        "encoder.encoders.3":"encoder.alayerblock2.0",
        "encoder.encoders.4":"encoder.alayerblock2.1",
        "encoder.encoders.5":"encoder.alayerblock2.2",
        "encoder.encoders.6":"encoder.alayerblock2.3",
        "encoder.encoders.7":"encoder.alayerblock2.4",
        "encoder.encoders.8":"encoder.alayerblock2.5",
        "encoder.encoders.9":"encoder.alayerblock2.6",
        "encoder.encoders.10":"encoder.alayerblock2.7",
        "encoder.encoders.11":"encoder.alayerblock2.8"}
    
            

# hybrid CTC/attention
model_conf:
    ctc_weight: 0.3
    lsm_weight: 0.1     
    length_normalized_loss: false

# minibatch related
batch_type: bucket
bucket_bsize_dynamic: True #
max_batch_size: 24 
bucket_length_multiplier: 1.1
bucket_batch_size: 2  

# optimization related
accum_grad: 4
grad_clip: 5
max_epoch: 40
val_scheduler_criterion:
    - valid
    - acc
best_model_criterion:
-   - valid
    - acc
    - max
keep_nbest_models: 10

optim: adam
optim_conf:
   lr: 0.0006
scheduler: warmuplr
scheduler_conf:
   warmup_steps: 6000

frontend: default
frontend_conf:
    win_length: 400
    hop_length: 160
    n_mels: &n_mels 80

preencoder: vggfeat
preencoder_conf:
    out_channels: [64,128]
    conv_kernel_size: [3,3]
    pooling_kernel_size: [2,2]
    num_conv_layers: [2,2]
    layer_norm: true
    input_feat_per_channel: *n_mels
    encoder_output_dim: *encoder_output_dim

videofront_conf: 
    random: True,
    channel_input: "bgr"
    size: [88,88]
    downsampling: False
    hidden_channel_num: 64

model_index: 10

specaug: specaug
specaug_conf:
    apply_time_warp: true
    time_warp_window: 5
    time_warp_mode: bicubic
    apply_freq_mask: false
    apply_time_mask: true
    time_mask_width_range:
    - 0
    - 40
    num_time_mask: 2

num_workers: 10
